import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Poppins } from "next/font/google";
import Navbar from "../components/Navbar";
import Footer from "@/components/Footer";

// Local font configuration
const mokotoVF = localFont({
  src: "./fonts/mokoto.woff",
  variable: "--font-mokoto",
  weight: "100 900",
});

// Google font configuration
const poppins = Poppins({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${mokotoVF.variable} ${poppins.className} antialiased`}
        >
          <Navbar /> {/* Include Navbar */}
          <main>{children}</main>
          <Footer /> {/* Include Footer */}
        </body>
      </html>
    </ClerkProvider>
  );
}
