import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {Poppins} from "next/font/google"
import Navbar from "./components/Navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const mokotoVF=localFont({
  src:"./fonts/mokoto.woff",
  variable:"--font-mokoto",
  weight: "100 900",
})
const poppins=Poppins({
  subsets:["latin"],
  weight:"400",
  display:"swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mokotoVF.variable} ${poppins.className} antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
